### ISSUE TITLE
about gpus memory

### ISSUE THREAD

**Issue by csxieyc97** [nv-nguyen/gigapose#9]
Can the code run on a GPU with ≤ 24GB of VRAM?

**Comment by wetoo-cando** [comment]
I get the following on a 24GB VRAM machine:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.18 GiB (GPU 0; 23.64 GiB total capacity; 18.12 GiB already allocated; 1.88 GiB free; 20.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

How should I adjust the code?

**Comment by nv-nguyen** [comment]
Hi guys, I am so sorry for my late reply!

Please check out my latest commit. I fixed this memory problem by limiting the [number of detections per image forwarded to 4](https://github.com/nv-nguyen/gigapose/blob/main/configs/test.yaml#L20) (before all detections were forwarded at once).

It only requires much less memory now, ~10-12GB. Please don't hesitate re-open the issue if there is any problems.
